### ISSUE TITLE
Can't find Spotify-AdKiller.cfg

### ISSUE THREAD

**Issue by ohnoplus** [SecUpwN/Spotify-AdKiller#31]
I do have the directory `$HOME/.config/Spotify-AdKiller/` but there is no `$HOME/.config/Spotify-AdKiller/Spotify-AdKiller.cfg` file.
Am I supposed to do something to make this file appear, or write it manually?
Ultimately, I am trying to like to switch the mode from continuous to simple.

**Comment by Feltzer** [comment]
Hi,

the config file is written automatically when the installation script or the wrapper script are run for the first time. Why this didn't work in your case I don't know. Could you please run the installer (install.sh) again in a terminal and post the output here? 

Of course you can always just copy the default configuration file from the zip file / cloned repository into the config directory, but it would be nice to know what went wrong during the installation.

HTH.

**Comment by SecUpwN** [comment]
@ohnoplus, please update this Issue with the requested output above. If the second try did work now, please close this Issue, otherwise I will do so on **wednesday** at the latest. Thanks or understanding.

**Comment by ohnoplus** [comment]
@Feltzer could you please extend this deadline to Friday. I am super busy the next two days but do want to get to the bottom of this.

**Comment by Feltzer** [comment]
@ohnoplus  Sure, no problem.

**Comment by ohnoplus** [comment]
Thanks for waiting. The command still did not create the config file; see below for command line output.

$: sudo . installh
## Changing permissions ##
mode of ‘spotify-adkiller.sh’ retained as 0775 (rwxrwxr-x)
mode of ‘spotify-wrapper.sh’ retained as 0775 (rwxrwxr-x)

## Creating installation directories ##

## Installing files ##
‘spotify-adkiller.sh’ -> ‘/home/ohnoplus/bin/spotify-adkiller.sh’
‘spotify-wrapper.sh’ -> ‘/home/ohnoplus/bin/spotify-wrapper.sh’
‘Spotify (AdKiller).desktop’ -> ‘/home/ohnoplus/.local/share/applications/Spotify (AdKiller).desktop’

**Comment by Feltzer** [comment]
Thanks for the install log. I think I found the issue: The installer was checking for an existing configuration file (in order not to overwrite any settings set by the user), but instead of looking in the actual config directory it was looking in the working directory. This should be fixed with 14bbbc3ffd723df7355cfbda8ae55735d422b343.

On another note: I noticed that you used `sudo` to run the installer. That's unnecessary and might in fact lead to some other problems (with permissions and such). Please just run `./install.sh` without root. If you actually do want to install this script system-wide, i.e. make it available to all users, you will have to follow the manual installation instructions provided in the README.

In any case, please try installing Spotify-AdKiller one more time. It should work now.

**Comment by ohnoplus** [comment]
Yep. The new version seems to work as expected. Thanks!
