### ISSUE TITLE
Play Bell sound loop

### ISSUE THREAD

**Issue by dokker** [SecUpwN/Spotify-AdKiller#32]
When I set CUSTOM_MODE to interstitial the random track starts to play from my chosen directory flawlessly.
In addition a bell starts to play continously from /usr/share/sounds/freedesktop/stereo location. It doesn't stop after the playback change back to spotify.

(By the way It's an awesome script. Big thanks to you!)

**Comment by VincentChalnot** [comment]
Same thing here, I'm on KUbuntu and the beep stops if I kill VLC.

**Comment by Feltzer** [comment]
Thanks for the reports, guys.

Looks like VLC remembers the repeat setting across sessions, so when the mode is set to interstitial the audio alert will also be played on repeat. I hadn't come across this bug because I was using mpv on my system.

Seeing how the audio alert was annoying anyway and didn't serve much of a purpose next to the GUI notifications, I decided to remove it (6b6252cc0626633a1d5700d0cfb9ddde940d1d75). Please give the latest master branch a try. The bell should be gone now.

**Comment by OlegSmelov** [comment]
@Feltzer `vlc` has a `--play-and-exit` parameter, perhaps that can help?

**Comment by Feltzer** [comment]
Yeah, the funny thing is that without `play-and-exit` `cvlc` wouldn't exit in the first place - even when there's no repeat and the playlist is over.

VLC has quite a few quirks like that, I found. For instance, GUI and CLI sessions share settings like repeat and volume. So if you set VLC to repeat a video and then mute it, next time you run `cvlc` to listen to an mp3 you will end up with silence on repeat, and with no way of discerning what the issue is. Very strange behaviour if you ask me.

**Comment by SecUpwN** [comment]
Thanks for solving bugs like these without my intervention, @Feltzer and @OlegSmelov. I'm still very happy to have you in my team of Collaborators for this project. Also thanks for the warm words, @dokker!

**Comment by VincentChalnot** [comment]
A big thanks for all of you, this project rock :+1:

**Comment by dokker** [comment]
It works fine now. Thanks!
